/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package medicalrecords;

/**
 *
 * @author marii
 */
public class FrmMedicalRecord extends javax.swing.JFrame implements clinic.views<MedicalRecord> {
    private clinic.ClinicControler controller;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMedicalRecord.class.getName());

    /**
     * Creates new form FrmMedicalRecord
     */
    
    public FrmMedicalRecord() {
        initComponents();
    controller = clinic.ClinicControler.getInstance(this);
    controller.setView(this);

    jDateChooser1.setDate(new java.util.Date());
    jDateChooser1.setEnabled(false);

    setLocationRelativeTo(null);
    }
    
    @Override
    public void clear() {
    txtConsultationReason.setText("");
    txtDiagnosis.setText("");
    txtTreatment.setText("");
    txtNotes.setText("");
    jDateChooser1.setDate(new java.util.Date());

    txtConsultationReason.requestFocus();
}
    @Override
    public void showData(MedicalRecord data) {
    if (data == null) {
        return;
    }

    jDateChooser1.setDate(
            java.sql.Date.valueOf(data.getDate())
    );

    txtConsultationReason.setText(
            data.getConsultationReason()
    );

    txtDiagnosis.setText(data.getDiagnosis());
    txtTreatment.setText(data.getTreatment());
    txtNotes.setText(data.getNotes());
}
    @Override
    public void showMessage(String message) {
    javax.swing.JOptionPane.showMessageDialog(
            this,
            message,
            "Registro médico",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
    );

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        lblMainTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        pnlConsultationReason = new javax.swing.JPanel();
        lblConsultationReason = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtConsultationReason = new javax.swing.JTextArea();
        pnlDiagnosis = new javax.swing.JPanel();
        lblDiagnosis = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDiagnosis = new javax.swing.JTextArea();
        pnlTreatment = new javax.swing.JPanel();
        lblTreatment = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtTreatment = new javax.swing.JTextArea();
        pnlNotes = new javax.swing.JPanel();
        lblNotes = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Medical Record");
        setResizable(false);

        pnlMain.setBackground(new java.awt.Color(250, 247, 242));

        lblMainTitulo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        lblMainTitulo.setForeground(new java.awt.Color(23, 74, 74));
        lblMainTitulo.setText("Registro Medico");

        lblSubtitulo.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(23, 74, 74));
        lblSubtitulo.setText("Complete los datos de atención medica");

        lblFecha.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(23, 74, 74));
        lblFecha.setText("Fecha:");

        pnlConsultationReason.setBackground(new java.awt.Color(255, 255, 255));
        pnlConsultationReason.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));

        lblConsultationReason.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        lblConsultationReason.setForeground(new java.awt.Color(23, 74, 74));
        lblConsultationReason.setText("Motivo de Consulta:");

        txtConsultationReason.setColumns(20);
        txtConsultationReason.setRows(5);
        jScrollPane1.setViewportView(txtConsultationReason);

        javax.swing.GroupLayout pnlConsultationReasonLayout = new javax.swing.GroupLayout(pnlConsultationReason);
        pnlConsultationReason.setLayout(pnlConsultationReasonLayout);
        pnlConsultationReasonLayout.setHorizontalGroup(
            pnlConsultationReasonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultationReasonLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblConsultationReason)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlConsultationReasonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pnlConsultationReasonLayout.setVerticalGroup(
            pnlConsultationReasonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultationReasonLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblConsultationReason)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pnlDiagnosis.setBackground(new java.awt.Color(255, 255, 255));
        pnlDiagnosis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));

        lblDiagnosis.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        lblDiagnosis.setForeground(new java.awt.Color(23, 74, 74));
        lblDiagnosis.setText("Diagnóstico:");

        txtDiagnosis.setColumns(20);
        txtDiagnosis.setRows(5);
        jScrollPane2.setViewportView(txtDiagnosis);

        javax.swing.GroupLayout pnlDiagnosisLayout = new javax.swing.GroupLayout(pnlDiagnosis);
        pnlDiagnosis.setLayout(pnlDiagnosisLayout);
        pnlDiagnosisLayout.setHorizontalGroup(
            pnlDiagnosisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDiagnosisLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblDiagnosis)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlDiagnosisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDiagnosisLayout.setVerticalGroup(
            pnlDiagnosisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDiagnosisLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblDiagnosis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTreatment.setBackground(new java.awt.Color(255, 255, 255));
        pnlTreatment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));

        lblTreatment.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        lblTreatment.setForeground(new java.awt.Color(23, 74, 74));
        lblTreatment.setText("Tratamiento:");

        txtTreatment.setColumns(20);
        txtTreatment.setRows(5);
        jScrollPane3.setViewportView(txtTreatment);

        javax.swing.GroupLayout pnlTreatmentLayout = new javax.swing.GroupLayout(pnlTreatment);
        pnlTreatment.setLayout(pnlTreatmentLayout);
        pnlTreatmentLayout.setHorizontalGroup(
            pnlTreatmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTreatmentLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTreatment)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlTreatmentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTreatmentLayout.setVerticalGroup(
            pnlTreatmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTreatmentLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTreatment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        pnlNotes.setBackground(new java.awt.Color(255, 255, 255));
        pnlNotes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));

        lblNotes.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        lblNotes.setForeground(new java.awt.Color(23, 74, 74));
        lblNotes.setText("Notas Adicionales:");

        txtNotes.setColumns(20);
        txtNotes.setRows(5);
        jScrollPane4.setViewportView(txtNotes);

        javax.swing.GroupLayout pnlNotesLayout = new javax.swing.GroupLayout(pnlNotes);
        pnlNotes.setLayout(pnlNotesLayout);
        pnlNotesLayout.setHorizontalGroup(
            pnlNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNotesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblNotes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlNotesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        pnlNotesLayout.setVerticalGroup(
            pnlNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNotesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblNotes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnBack.setBackground(new java.awt.Color(250, 255, 255));
        btnBack.setForeground(new java.awt.Color(23, 74, 74));
        btnBack.setText("Regresar");
        btnBack.addActionListener(this::btnBackActionPerformed);

        btnClean.setBackground(new java.awt.Color(249, 211, 203));
        btnClean.setForeground(new java.awt.Color(145, 72, 60));
        btnClean.setText("Limpiar");
        btnClean.addActionListener(this::btnCleanActionPerformed);

        btnSave.setBackground(new java.awt.Color(23, 74, 74));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Guardar Registro");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMainTitulo)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pnlTreatment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSubtitulo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlConsultationReason, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(86, 86, 86)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addComponent(lblFecha)
                                .addGap(31, 31, 31)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnlDiagnosis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlNotes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(40, 40, 40)
                .addComponent(btnClean)
                .addGap(50, 50, 50)
                .addComponent(btnSave)
                .addGap(101, 101, 101))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblMainTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSubtitulo)
                        .addComponent(lblFecha))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDiagnosis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlConsultationReason, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlNotes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTreatment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnClean)
                    .addComponent(btnSave))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String consultationReason =
            txtConsultationReason.getText().trim();

    String diagnosis =
            txtDiagnosis.getText().trim();

    String treatment =
            txtTreatment.getText().trim();

    String notes =
            txtNotes.getText().trim();

    if (consultationReason.isEmpty()
            || diagnosis.isEmpty()
            || treatment.isEmpty()) {

        showError(
                "Debe completar el motivo de consulta, "
                + "el diagnóstico y el tratamiento"
        );

        return;
    }
    
    boolean saved = controller.addMedicalRecord(
            consultationReason,
            diagnosis,
            treatment,
            notes
    );

    if (saved) {
        clear();
    }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        clear();
    }//GEN-LAST:event_btnCleanActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMedicalRecord().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnSave;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblConsultationReason;
    private javax.swing.JLabel lblDiagnosis;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblMainTitulo;
    private javax.swing.JLabel lblNotes;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTreatment;
    private javax.swing.JPanel pnlConsultationReason;
    private javax.swing.JPanel pnlDiagnosis;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlNotes;
    private javax.swing.JPanel pnlTreatment;
    private javax.swing.JTextArea txtConsultationReason;
    private javax.swing.JTextArea txtDiagnosis;
    private javax.swing.JTextArea txtNotes;
    private javax.swing.JTextArea txtTreatment;
    // End of variables declaration//GEN-END:variables


    @Override
    public void showError(String error) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
