/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinic;
import medicalrecords.FrmMedicalRecord;
/**
 *
 * @author marii
 */
public class FrmClinic extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmClinic.class.getName());

    /**
     * Creates new form FrmClinic
     */
    public FrmClinic() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        pnlMain = new javax.swing.JPanel();
        lblMainTitle = new javax.swing.JLabel();
        lblMainTitle1 = new javax.swing.JLabel();
        pnlPatients = new javax.swing.JPanel();
        lblPacientes = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pnlPatients1 = new javax.swing.JPanel();
        lblPacientes1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        pnlPatients2 = new javax.swing.JPanel();
        lblPacientes2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        pnlPatients3 = new javax.swing.JPanel();
        lblPacientes3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clinica Medica");
        setResizable(false);

        pnlMain.setBackground(new java.awt.Color(250, 247, 242));

        lblMainTitle.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        lblMainTitle.setForeground(new java.awt.Color(41, 56, 56));
        lblMainTitle.setText("Clinic Menú Principal");

        lblMainTitle1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lblMainTitle1.setForeground(new java.awt.Color(41, 56, 56));
        lblMainTitle1.setText("Seleccione el área que desea consultar:");

        pnlPatients.setBackground(new java.awt.Color(255, 255, 255));
        pnlPatients.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(195, 215, 208)));

        lblPacientes.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lblPacientes.setForeground(new java.awt.Color(23, 74, 74));
        lblPacientes.setText("Pacients");

        jButton1.setBackground(new java.awt.Color(221, 237, 232));
        jButton1.setForeground(new java.awt.Color(23, 74, 74));
        jButton1.setText("Ingrese a Pacients");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout pnlPatientsLayout = new javax.swing.GroupLayout(pnlPatients);
        pnlPatients.setLayout(pnlPatientsLayout);
        pnlPatientsLayout.setHorizontalGroup(
            pnlPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPatientsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlPatientsLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(lblPacientes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPatientsLayout.setVerticalGroup(
            pnlPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPatientsLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lblPacientes)
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPatients1.setBackground(new java.awt.Color(255, 255, 255));
        pnlPatients1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(127, 175, 195)));

        lblPacientes1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lblPacientes1.setForeground(new java.awt.Color(23, 74, 74));
        lblPacientes1.setText("Medical Record");

        jButton2.setBackground(new java.awt.Color(218, 235, 242));
        jButton2.setForeground(new java.awt.Color(43, 105, 133));
        jButton2.setText("Ingrese a Medical Record");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout pnlPatients1Layout = new javax.swing.GroupLayout(pnlPatients1);
        pnlPatients1.setLayout(pnlPatients1Layout);
        pnlPatients1Layout.setHorizontalGroup(
            pnlPatients1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPatients1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlPatients1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(lblPacientes1)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        pnlPatients1Layout.setVerticalGroup(
            pnlPatients1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPatients1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lblPacientes1)
                .addGap(30, 30, 30)
                .addComponent(jButton2)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pnlPatients2.setBackground(new java.awt.Color(255, 255, 255));
        pnlPatients2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 130, 114)));

        lblPacientes2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lblPacientes2.setForeground(new java.awt.Color(23, 74, 74));
        lblPacientes2.setText("Appointments");

        jButton3.setBackground(new java.awt.Color(249, 211, 203));
        jButton3.setForeground(new java.awt.Color(179, 83, 64));
        jButton3.setText("Ingrese a Appointments");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout pnlPatients2Layout = new javax.swing.GroupLayout(pnlPatients2);
        pnlPatients2.setLayout(pnlPatients2Layout);
        pnlPatients2Layout.setHorizontalGroup(
            pnlPatients2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPatients2Layout.createSequentialGroup()
                .addGroup(pnlPatients2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPatients2Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jButton3))
                    .addGroup(pnlPatients2Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(lblPacientes2)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        pnlPatients2Layout.setVerticalGroup(
            pnlPatients2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPatients2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(lblPacientes2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPatients3.setBackground(new java.awt.Color(255, 255, 255));
        pnlPatients3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 130, 114)));

        lblPacientes3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lblPacientes3.setForeground(new java.awt.Color(23, 74, 74));
        lblPacientes3.setText("Citas de Hoy");

        jButton4.setBackground(new java.awt.Color(229, 234, 218));
        jButton4.setForeground(new java.awt.Color(86, 113, 72));
        jButton4.setText("Ingrese a Citas Hoy");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        javax.swing.GroupLayout pnlPatients3Layout = new javax.swing.GroupLayout(pnlPatients3);
        pnlPatients3.setLayout(pnlPatients3Layout);
        pnlPatients3Layout.setHorizontalGroup(
            pnlPatients3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPatients3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlPatients3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPatients3Layout.createSequentialGroup()
                        .addComponent(lblPacientes3)
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPatients3Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(95, 95, 95))))
        );
        pnlPatients3Layout.setVerticalGroup(
            pnlPatients3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPatients3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(lblPacientes3)
                .addGap(32, 32, 32)
                .addComponent(jButton4)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMainTitle)
                            .addComponent(lblMainTitle1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pnlPatients2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlPatients, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlPatients3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlPatients1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(50, Short.MAX_VALUE))))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblMainTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMainTitle1)
                .addGap(18, 18, 18)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlPatients1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPatients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlPatients3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPatients2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        FrmMedicalRecord medicalRecordView = new FrmMedicalRecord();

        medicalRecordView.setLocationRelativeTo(this);
        medicalRecordView.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmClinic().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel lblMainTitle;
    private javax.swing.JLabel lblMainTitle1;
    private javax.swing.JLabel lblPacientes;
    private javax.swing.JLabel lblPacientes1;
    private javax.swing.JLabel lblPacientes2;
    private javax.swing.JLabel lblPacientes3;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlPatients;
    private javax.swing.JPanel pnlPatients1;
    private javax.swing.JPanel pnlPatients2;
    private javax.swing.JPanel pnlPatients3;
    // End of variables declaration//GEN-END:variables
}
